#!/usr/bin/env bash

set -e

FILES="./src/v0.8/ccip/test/publicABI/*"

for f in $FILES
do
  expectedAbi=$( cat $f | tr -d " \t\n\r" )

  fileName=$( echo "$f" | sed "s/.*\///" )
  echo "Checking $fileName"
  
  actualAbi=$( forge inspect $fileName methods | tr -d " \t\n\r" )

  if [[ "$expectedAbi" != "$actualAbi" ]]; then
    printf "ERROR: $fileName ABI does not match expected ABI. Try running this command:\n\n"
    printf "make ccip-abi-fix\n\n"
    exit 1
  fi

done

echo "ABI check successful"