[havoc]
# dir is a custom dir you can select, if null monkey will create a new dir
dir = "experiments"
# pods with this prefix will be ignored when generating experiments
ignore_pods = ["-db-"]
# name of the key to select components in the namespace
component_label_key = "havoc-component-group"
# group labels containing these strings will be ignored when generating group experiments
ignore_group_labels = [
    "mainnet",
    "release",
    "intents.otterize.com",
    "pod-template-hash",
    "rollouts-pod-template-hash",
    "chain.link/app",
    "chain.link/cost-center",
    "chain.link/env",
    "chain.link/project",
    "chain.link/team",
    "app.kubernetes.io/part-of",
    "app.kubernetes.io/managed-by",
    "app.chain.link/product",
    "app.kubernetes.io/version",
    "app.chain.link/blockchain",
    "app.kubernetes.io/instance",
    "app.kubernetes.io/name",
]
# these are experiment types you'd like to generate
experiment_types = [
    "external",
    "failure",
    "latency",
    "cpu",
    "memory",
    "group-failure",
    "group-latency",
    "group-cpu",
    "group-memory",
    "group-partition",
    "blockchain_rewind_head",
]

[havoc.failure]
# duration of a "failure" experiment
duration = "30s"
# percentage of pods experiments affect in groups, see group-failure key and dir when generated
group_fixed = ["3", "2", "1"]

[havoc.latency]
# duration of "latency" experiment
duration = "30s"
# constant latency to inject
latency = "300ms"
# percentage of pods experiments affect in groups, see group-failure key and dir when generated
group_fixed = ["2", "1"]

[havoc.stress_memory]
# duration of "stress" experiment affecting pod memory
duration = "30s"
# amount of workers which occupies memory
workers = 1
# total amount of memory occupied
memory = "512MB"
# number of pods experiments affect in groups, see group-failure key and dir when generated
group_fixed = ["3", "2", "1"]

[havoc.stress_cpu]
# duration of "stress" experiment affecting pod CPU
duration = "30s"
# amount of workers which occupies cpu
workers = 1
# amount of CPU core utilization, 100 means 1 worker will consume 1 cpu, 2 workers + 100 load = 2 CPUs
load = 100
# number of pods experiments affect in groups, see group-failure key and dir when generated
group_fixed = ["3", "2", "1"]

[havoc.network_partition]
# duration of "network partition" experiment affecting pod CPU
duration = "30s"
# percentage of pods experiments affect in groups, see group-failure key and dir when generated
group_percentage = ["100"]
# a label to split pods for experiments
label = "havoc-network-group"

[havoc.blockchain_rewind_head]
# duration of "blockchain" experiment
duration = "30s"
# label of executor pod
executor_pod_prefix = "geth-1337"
# executor container name
executor_container_name = "geth-network"
# blockchain node internal HTTP URL
node_internal_http_url = "geth-1337:8544"
# blocks to rewind from last
blocks = [50, 40, 30, 20, 10]

[havoc.external_targets]
# duration of "external" experiment
duration = "30s"
# URL of external service that'd fail to resolve
urls = ["www.google.com"]

[havoc.monkey]
# havoc monkey mode:
# seq - runs all experiments from all dirs sequentially one time
# rand - runs random experiments from all dirs
mode = "rand"
# duration of havoc monkey
duration = "10m"
# cooldown between experiments
cooldown = "30s"

[havoc.grafana]
# UIDs of dashboard which should be annotated with chaos experiments metadata
# You can also try to use name as you see it in the top bar of your dashboard but that's not guaranteed to match
dashboard_uids = ["d1d95a37-eb66-474d-bdc7-25897e4b5f3b"]
