version: 2
project_name: ccip
env:
  - ZIG_EXEC={{ if index .Env "ZIG_EXEC"  }}{{ .Env.ZIG_EXEC }}{{ else }}zig{{ end }}
  - IMAGE_LABEL_DESCRIPTION="node of the decentralized oracle network, bridging on and off-chain computation"
  - IMAGE_LABEL_LICENSES="MIT"
  - IMAGE_LABEL_SOURCE="https://github.com/smartcontractkit/{{ .ProjectName }}"

before:
  hooks:
    - go mod tidy
    - ./tools/bin/goreleaser_utils before_hook

# See https://goreleaser.com/customization/build/
builds:
  - binary: chainlink
    id: linux-amd64
    goos:
      - linux
    goarch:
      - amd64
    hooks:
        - cmd: go mod tidy
        - cmd: ./tools/bin/goreleaser_utils before_hook
git:
    ignore_tags:
        - contracts-ccip/v1.5.0-beta.0
partial:
    by: target
nightly:
    version_template: v0.0.0-{{ .Runtime.Goarch }}-{{ .Now.Format "2006-01-02-15-04-05Z" }}
