// Code generated by mockery v2.28.1. DO NOT EDIT.

package ccipdata

import (
	context "context"

	common "github.com/ethereum/go-ethereum/common"

	evm_2_evm_onramp "github.com/smartcontractkit/chainlink/v2/core/gethwrappers/ccip/generated/evm_2_evm_onramp"
	internal "github.com/smartcontractkit/chainlink/v2/core/services/ocr2/plugins/ccip/internal"

	mock "github.com/stretchr/testify/mock"

	pg "github.com/smartcontractkit/chainlink/v2/core/services/pg"
)

// MockOnRampReader is an autogenerated mock type for the OnRampReader type
type MockOnRampReader struct {
	mock.Mock
}

// Close provides a mock function with given fields: qopts
func (_m *MockOnRampReader) Close(qopts ...pg.QOpt) error {
	_va := make([]interface{}, len(qopts))
	for _i := range qopts {
		_va[_i] = qopts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(...pg.QOpt) error); ok {
		r0 = rf(qopts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOnRampAddress provides a mock function with given fields:
func (_m *MockOnRampReader) GetOnRampAddress() (common.Address, error) {
	ret := _m.Called()

	var r0 common.Address
	var r1 error
	if rf, ok := ret.Get(0).(func() (common.Address, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() common.Address); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Address)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOnRampDynamicConfig provides a mock function with given fields:
func (_m *MockOnRampReader) GetOnRampDynamicConfig() (evm_2_evm_onramp.EVM2EVMOnRampDynamicConfig, error) {
	ret := _m.Called()

	var r0 evm_2_evm_onramp.EVM2EVMOnRampDynamicConfig
	var r1 error
	if rf, ok := ret.Get(0).(func() (evm_2_evm_onramp.EVM2EVMOnRampDynamicConfig, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() evm_2_evm_onramp.EVM2EVMOnRampDynamicConfig); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(evm_2_evm_onramp.EVM2EVMOnRampDynamicConfig)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSendRequestsBetweenSeqNums provides a mock function with given fields: ctx, seqNumMin, seqNumMax, confs
func (_m *MockOnRampReader) GetSendRequestsBetweenSeqNums(ctx context.Context, seqNumMin uint64, seqNumMax uint64, confs int) ([]Event[internal.EVM2EVMMessage], error) {
	ret := _m.Called(ctx, seqNumMin, seqNumMax, confs)

	var r0 []Event[internal.EVM2EVMMessage]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64, int) ([]Event[internal.EVM2EVMMessage], error)); ok {
		return rf(ctx, seqNumMin, seqNumMax, confs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64, int) []Event[internal.EVM2EVMMessage]); ok {
		r0 = rf(ctx, seqNumMin, seqNumMax, confs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Event[internal.EVM2EVMMessage])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, uint64, int) error); ok {
		r1 = rf(ctx, seqNumMin, seqNumMax, confs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSendRequestsGteSeqNum provides a mock function with given fields: ctx, seqNum, confs
func (_m *MockOnRampReader) GetSendRequestsGteSeqNum(ctx context.Context, seqNum uint64, confs int) ([]Event[internal.EVM2EVMMessage], error) {
	ret := _m.Called(ctx, seqNum, confs)

	var r0 []Event[internal.EVM2EVMMessage]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, int) ([]Event[internal.EVM2EVMMessage], error)); ok {
		return rf(ctx, seqNum, confs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, int) []Event[internal.EVM2EVMMessage]); ok {
		r0 = rf(ctx, seqNum, confs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Event[internal.EVM2EVMMessage])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, int) error); ok {
		r1 = rf(ctx, seqNum, confs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RouterAddress provides a mock function with given fields:
func (_m *MockOnRampReader) RouterAddress() (common.Address, error) {
	ret := _m.Called()

	var r0 common.Address
	var r1 error
	if rf, ok := ret.Get(0).(func() (common.Address, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() common.Address); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Address)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockOnRampReader interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockOnRampReader creates a new instance of MockOnRampReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockOnRampReader(t mockConstructorTestingTNewMockOnRampReader) *MockOnRampReader {
	mock := &MockOnRampReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
