apiVersion: batch/v1
kind: Job
metadata:
  name: ccip-scripts-deploy
  labels:
    app: ccip-scripts-deployer
  annotations:
    prometheus.io/scrape: 'true'
spec:
  template:
    metadata:
      labels:
        app: ccip-scripts-deployer
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: ccip-scripts
          image: {{.Values.ccip.ccipScriptsImage}}
          env:
            - name: CONFIG_JSON_PATH
              value: /data/config.json
          command: [  "pilot.test", "-test.v" ]
          volumeMounts:
            - name: config-volume
              mountPath: /data
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsUser: 999
            runAsGroup: 999
            runAsNonRoot: true
      restartPolicy: Never
      volumes:
        - name: config-volume
          configMap:
            name: ccip-scripts-config
  backoffLimit: 1
