apiVersion: v1
kind: ConfigMap
metadata:
  name: ccip-scripts-config
data:
  config.json: |
    {
      "EnvName": "{{$.Release.Namespace}}",
      "DONCreds": {
        "Env": "{{$.Release.Namespace}}",
        "Bootstrap": {
           {{- with (index $.Values.chainlink.nodes 0) }}
           {{- $nameWithoutHyphen := .name | replace "-" "" }}
          "URL": "https://{{$.Release.Namespace}}-{{$nameWithoutHyphen}}.{{$.Values.ingress.baseDomain}}/",
          "Email": "notreal@fakeemail.ch",
          "Password": "fj293fbBnlQ!f9vNs",
          "InternalIP": "{{$.Release.Name}}-{{.name}}",
          {{- end}}
          "HTTPTimeout": null
        },
        "Nodes": [
          {{- range $index, $cfg := $.Values.chainlink.nodes }}
            {{- if ne $index 0}}
            {{- $nameWithoutHyphen := $cfg.name | replace "-" "" }}
          {{- if ne $index 1 }},{{- end }}{
            "URL": "https://{{$.Release.Namespace}}-{{$nameWithoutHyphen}}.{{$.Values.ingress.baseDomain}}/",
            "Email": "notreal@fakeemail.ch",
            "Password": "fj293fbBnlQ!f9vNs",
            "InternalIP": "{{$.Release.Name}}-{{$cfg.name}}",
            "HTTPTimeout": null
          }
            {{- end}}
          {{- end}}
        ]
      },
      {{- $networkIDs := list }}
      {{- range $index, $cfg :=$.Values.ccip.chains }}
        {{- $networkIDs = append $networkIDs $cfg.ChainId }}
      {{- end }}

      {{- $delimiter := "," }}
      {{- $foldedString := join $delimiter $networkIDs }}
      "ChainPairs":[{{- printf $foldedString | quote }}],
      "CCIPChains": {
        {{- range $index, $cfg := $.Values.ccip.chains }}
        {{- if ne $index 0 }},{{- end }}"{{$cfg.ChainId}}":{
          "NetworkURL": "wss://{{$.Release.Namespace}}-geth-{{$cfg.NetworkId}}-ws.{{$.Values.ingress.baseDomain}}",
          "WalletKey": {{$cfg.WalletKey | quote}},
          "DeployLink": {{$cfg.DeployLink}},
          "DeployWETH": {{$cfg.DeployWETH}},
          "ChainConfig": {{$cfg.ChainConfig | toJson}}
        }
        {{- end}}
      },
      "LaneDeploySettings": {{$.Values.ccip.LaneDeploySettings | toJson }}
    }

---
apiVersion: v1
kind: Pod
metadata:
  name: ccip-scripts-deploy

spec:
  containers:
    - name: ccip-scripts
      image: {{.Values.ccip.ccipScriptsImage}}
      env:
        - name: CONFIG_JSON_PATH
          value: /data/config.json
      command:
        - "tail"
        - "-f"
        - "/dev/null"
      volumeMounts:
        - name: config-volume
          mountPath: /data
      securityContext:
        capabilities:
          drop:
            - ALL
        runAsUser: 999
        runAsGroup: 999
        runAsNonRoot: true
  restartPolicy: Never
  volumes:
    - name: config-volume
      configMap:
        name: ccip-scripts-config
    - name: build-volume
      emptyDir: {}

