{{if .Values.ccip.debug }}
apiVersion: v1
kind: Pod
metadata:
  name: ccip-scripts-deploy
  labels:
    app: ccip-scripts-deployer
  annotations:
    prometheus.io/scrape: 'true'
spec:
  containers:
    - name: ccip-scripts
      image: {{.Values.ccip.ccipScriptsImage}}
      env:
        - name: CONFIG_JSON_PATH
          value: /data/config.json
      command:
        - "tail"
        - "-f"
        - "/dev/null"
      volumeMounts:
        - name: config-volume
          mountPath: /data
      securityContext:
        capabilities:
          drop:
            - ALL
        runAsUser: 999
        runAsGroup: 999
        runAsNonRoot: true
  restartPolicy: Never
  volumes:
    - name: config-volume
      configMap:
        name: ccip-scripts-config
{{end}}