// Code generated by mockery v2.10.1. DO NOT EDIT.

package mocks

import (
	bind "github.com/ethereum/go-ethereum/accounts/abi/bind"

	mock "github.com/stretchr/testify/mock"

	offramp "github.com/smartcontractkit/chainlink/core/internal/gethwrappers/generated/offramp"
)

// OffRampLastReporter is an autogenerated mock type for the OffRampLastReporter type
type OffRampLastReporter struct {
	mock.Mock
}

// GetLastReport provides a mock function with given fields: opts
func (_m *OffRampLastReporter) GetLastReport(opts *bind.CallOpts) (offramp.CCIPRelayReport, error) {
	ret := _m.Called(opts)

	var r0 offramp.CCIPRelayReport
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) offramp.CCIPRelayReport); ok {
		r0 = rf(opts)
	} else {
		r0 = ret.Get(0).(offramp.CCIPRelayReport)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*bind.CallOpts) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
