// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	common "github.com/ethereum/go-ethereum/common"
	ccipdata "github.com/smartcontractkit/chainlink/v2/core/services/ocr2/plugins/ccip/internal/ccipdata"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TokenPoolFactoryInterface is an autogenerated mock type for the TokenPoolFactoryInterface type
type TokenPoolFactoryInterface struct {
	mock.Mock
}

// NewTokenPools provides a mock function with given fields: ctx, tokenPoolAddresses
func (_m *TokenPoolFactoryInterface) NewTokenPools(ctx context.Context, tokenPoolAddresses []common.Address) ([]ccipdata.TokenPoolReader, error) {
	ret := _m.Called(ctx, tokenPoolAddresses)

	if len(ret) == 0 {
		panic("no return value specified for NewTokenPools")
	}

	var r0 []ccipdata.TokenPoolReader
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []common.Address) ([]ccipdata.TokenPoolReader, error)); ok {
		return rf(ctx, tokenPoolAddresses)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []common.Address) []ccipdata.TokenPoolReader); ok {
		r0 = rf(ctx, tokenPoolAddresses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ccipdata.TokenPoolReader)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []common.Address) error); ok {
		r1 = rf(ctx, tokenPoolAddresses)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTokenPoolFactoryInterface creates a new instance of TokenPoolFactoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenPoolFactoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenPoolFactoryInterface {
	mock := &TokenPoolFactoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
