[CCIP]
[CCIP.Deployments]
Data = """
{
    "lane_configs": {
      "Arbitrum Sepolia": {
        "is_mock_arm": true,
        "fee_token": "0xb1D4538B4571d411F07960EF2838Ce337FE1E80E",
        "bridge_tokens": [],
        "bridge_tokens_pools": [],
        "arm": "0x2aE6d5495fc20226F433be50e37D59c05D186AaA",
        "router": "0x0fF6b6F3Ad10D66600Fd5CC25b98542A05Aa7Bc2",
        "price_registry": "0x25d997d8618e1299418b3D905E40bC353ec89F61",
        "wrapped_native": "0xE591bf0A0CF924A0674d7792db046B23CEbF5f34",
        "src_contracts": {
          "Sepolia Testnet": {
            "on_ramp": "0x44225eb3B73B1b52Dd2ecD258F9b63418eC6Bf79",
            "deployed_at": 13730868
          }
        },
        "dest_contracts": {
          "Sepolia Testnet": {
            "off_ramp": "0xc136114F379b812345bb7e467ECDdb6D0c87De8b",
            "commit_store": "0x42b3EbEA14F6CB803e3C7df84392Efb85CE90168",
            "receiver_dapp": "0x8Ed27Ab67aea9BC50628fba25ab52D23ae8d0eae"
          }
        }
      },
      "Avalanche Fuji": {
        "is_mock_arm": true,
        "fee_token": "0x0b9d5D9136855f6FEc3c0993feE6E9CE8a297846",
        "bridge_tokens": null,
        "bridge_tokens_pools": null,
        "arm": "0xD4A51dC0F5C680A8A18eA4Ec3A2f25C6db9424B7",
        "router": "0xa62e685aDFF45f38eC94378513D128F168964E99",
        "price_registry": "0xdbeA1a10AC6a2B729bF128aE9281Ed420dbE7113",
        "wrapped_native": "0xd00ae08403B9bbb9124bB305C09058E32C39A48c",
        "src_contracts": {
          "Polygon Mumbai": {
            "on_ramp": "0x405737705aD3f2E472aAC31ad4477A332E54F4fF",
            "deployed_at": 29935179
          }
        },
        "dest_contracts": {
          "Polygon Mumbai": {
            "off_ramp": "0x572C4fc679D4Fe9652E413f4060E6d979101Ac66",
            "commit_store": "0x755b4a2472a720036527a806c95749D6623A392E",
            "receiver_dapp": "0x8Ed27Ab67aea9BC50628fba25ab52D23ae8d0eae"
          }
        }
      },
      "Polygon Mumbai": {
        "is_mock_arm": true,
        "fee_token": "0x326C977E6efc84E512bB9C30f76E30c160eD06FB",
        "bridge_tokens": null,
        "bridge_tokens_pools": null,
        "arm": "0x866faB92E04bAE5EDa238A9cbFf1e56E09508Ade",
        "router": "0x479A6fF9a2335180D92306D76754bBBDcA751bF0",
        "price_registry": "0xD886E2286Fd1073df82462ea1822119600Af80b6",
        "wrapped_native": "0x9c3C9283D3e44854697Cd22D3Faa240Cfb032889",
        "src_contracts": {
          "Avalanche Fuji": {
            "on_ramp": "0x2beC13D06d42278323008a3BAA364C277Ba411AB",
            "deployed_at": 45847832
          }
        },
        "dest_contracts": {
          "Avalanche Fuji": {
            "off_ramp": "0x14DF61c5F65C38d149329673e59bEC38d444dF48",
            "commit_store": "0x326Acbb36C4aE866bB5BaEaAd4163fE128A9f5B5",
            "receiver_dapp": "0x8Ed27Ab67aea9BC50628fba25ab52D23ae8d0eae"
          }
        }
      },
      "Sepolia Testnet": {
        "is_mock_arm": true,
        "fee_token": "0x779877A7B0D9E8603169DdbD7836e478b4624789",
        "bridge_tokens": [],
        "bridge_tokens_pools": [],
        "arm": "0x9912a7389382ff55f85A29C9378B38F7B992c4aE",
        "router": "0x1E1F3d8Ac7Df65fCcFcc52dbF03929cEE95430ac",
        "price_registry": "0x4358e81f88bB27222779c1BC85003A11A1c66f6F",
        "wrapped_native": "0x097D90c9d3E0B50Ca60e1ae45F6A81010f9FB534",
        "src_contracts": {
          "Arbitrum Sepolia": {
            "on_ramp": "0x420a7B5ABB8CF27A70E1906F797e24509B11093D",
            "deployed_at": 5275652
          }
        },
        "dest_contracts": {
          "Arbitrum Sepolia": {
            "off_ramp": "0x224D1eB3aB2b7F23b66f093F9cBBC68dA77a1986",
            "commit_store": "0x35c54cF12FF9B29dBa60dc23EdD1de0F13CC7fc5",
            "receiver_dapp": "0x8Ed27Ab67aea9BC50628fba25ab52D23ae8d0eae"
          }
        }
      }
    }
  }
"""

[CCIP.Env.Network]
selected_networks = ['SEPOLIA','ARBITRUM_SEPOLIA','AVALANCHE_FUJI','POLYGON_MUMBAI']

[CCIP.Groups.load]
NetworkPairs = ['ARBITRUM_SEPOLIA,SEPOLIA','AVALANCHE_FUJI,POLYGON_MUMBAI']
MsgType = 'WithoutToken'
PhaseTimeout = '50m'
TestDuration = '6h'
ExistingDeployment = true
RequestPerUnitTime = [1]
TimeUnit = '5m'
NoOfTokensPerChain = 1
NoOfTokensInMsg = 1
AmountPerToken = 1
TestRunName = 'beta-1.4.1'

[CCIP.Groups.smoke]
MsgType = 'WithoutToken'
NetworkPairs = ['AVALANCHE_FUJI,POLYGON_MUMBAI']
PhaseTimeout = '20m'
BiDirectionalLane = false
LocalCluster = false
ExistingDeployment = true
ReuseContracts = true
NoOfTokensPerChain = 1
NoOfTokensInMsg = 1
