[CCIP]
[CCIP.Deployments]
Data = """
{
    "lane_configs": {
      "Arbitrum Sepolia": {
        "is_native_fee_token": true,
        "fee_token": "0xd14838A68E8AFBAdE5efb411d5871ea0011AFd28",
        "bridge_tokens": [],
        "bridge_tokens_pools": [],
        "arm": "0x2f166b552b8cb5be706577057e09255cc81ec950",
        "router": "0x4405652c6450b959debf78470cc73c2c6607f44a",
        "price_registry": "0xe8ef2f84f6c0b99dbff784bcb8c1844c0bf3ac46",
        "wrapped_native": "0x980B62Da83eFf3D4576C647993b0c1D7faf17c73",
        "src_contracts": {
          "Sepolia Testnet": {
            "on_ramp": "0x0479e8ac30ae624b48442695b4a336b54710d5d0",
            "deployed_at": 11111111
          }
        },
        "dest_contracts": {
          "Sepolia Testnet": {
            "off_ramp": "0xe0c80917006b7c68d285cdd01ee74a9203019417",
            "commit_store": "0x769866ed89012cee514c5e036fd30fefd4e93508",
            "receiver_dapp": "0x5fD09c34fddeBEa3266E0dAd616A5657b23fE0aA"
          }
        }
      },
      "Sepolia Testnet": {
        "is_native_fee_token": true,
        "fee_token": "0x779877A7B0D9E8603169DdbD7836e478b4624789",
        "bridge_tokens": [],
        "bridge_tokens_pools": [],
        "arm": "0x6e5c46240cdd2f2d704ba0fb1c30a55d3b18cfd3",
        "router": "0xbaa005d96b9b8da5e59fc824c7f05e9d3c679e87",
        "price_registry": "0x5de7598e12aa9aecdd3125a2dab8050d4405448b",
        "wrapped_native": "0x097D90c9d3E0B50Ca60e1ae45F6A81010f9FB534",
        "src_contracts": {
          "Arbitrum Sepolia": {
            "on_ramp": "0x5de7598e12aa9aecdd3125a2dab8050d4405448b",
            "deployed_at": 11111111
          }
        },
        "dest_contracts": {
          "Arbitrum Sepolia": {
            "off_ramp": "0x0475b3f95fc9ac6ee9a125917d61c0759606eadf",
            "commit_store": "0xe8b7d8f6d2b7ee80dc628b3e9fabf4ad92dedf60",
            "receiver_dapp": "0x5fD09c34fddeBEa3266E0dAd616A5657b23fE0aA"
          }
        }
      }
    }
  }
"""

[CCIP.Groups.load]
NetworkPairs = ['SEPOLIA,OPTIMISM_GOERLI','SEPOLIA,POLYGON_MUMBAI','AVALANCHE_FUJI,SEPOLIA','SEPOLIA,BASE_GOERLI','SEPOLIA,BSC_TESTNET','SEPOLIA,WEMIX_TESTNET','AVALANCHE_FUJI,OPTIMISM_GOERLI','AVALANCHE_FUJI,POLYGON_MUMBAI','AVALANCHE_FUJI,BSC_TESTNET','AVALANCHE_FUJI,BASE_GOERLI','OPTIMISM_GOERLI,BASE_GOERLI','OPTIMISM_GOERLI,POLYGON_MUMBAI','BSC_TESTNET,POLYGON_MUMBAI','BSC_TESTNET,BASE_GOERLI','WEMIX_TESTNET,KROMA_SEPOLIA']
MsgType = 'WithoutToken'
PhaseTimeout = '50m'
TestDuration = '2h'
ExistingDeployment = true
RequestPerUnitTime = [1]
TimeUnit = '5m'
NoOfTokensPerChain = 1
NoOfTokensInMsg = 1
AmountPerToken = 1
ExistingEnv = 'prod-testnet-2.7.1-ccip1.2.1-beta'

[CCIP.Groups.smoke]
MsgType = 'WithoutToken'
NetworkPairs = ['ARBITRUM_SEPOLIA,SEPOLIA']
# NetworkPairs = ['SEPOLIA,OPTIMISM_GOERLI','SEPOLIA,POLYGON_MUMBAI','AVALANCHE_FUJI,SEPOLIA','SEPOLIA,BASE_GOERLI','SEPOLIA,BSC_TESTNET','SEPOLIA,WEMIX_TESTNET','AVALANCHE_FUJI,OPTIMISM_GOERLI','AVALANCHE_FUJI,POLYGON_MUMBAI','AVALANCHE_FUJI,BSC_TESTNET','AVALANCHE_FUJI,BASE_GOERLI','OPTIMISM_GOERLI,BASE_GOERLI','OPTIMISM_GOERLI,POLYGON_MUMBAI','BSC_TESTNET,POLYGON_MUMBAI','BSC_TESTNET,BASE_GOERLI','WEMIX_TESTNET,KROMA_SEPOLIA']
PhaseTimeout = '50m'
LocalCluster = false
ExistingDeployment = true
ReuseContracts = true
NoOfTokensPerChain = 1
NoOfTokensInMsg = 1
