[CCIP]

[CCIP.Env]
Networks = ['SEPOLIA', 'OPTIMISM_GOERLI']

[CCIP.Groups]
[CCIP.Groups.smoke]
KeepEnvAlive = false
BiDirectionalLane = false
CommitAndExecuteOnSameDON = true
MsgType = 'WithoutToken'
PhaseTimeout = '10m'
LocalCluster = false
ExistingDeployment = true
ReuseContracts = true
