[CCIP]
[CCIP.Env]
[CCIP.Env.Chainlink]
NoOfNodes = 16
NodeMemory = '6Gi'
NodeCPU = '4'
DBMemory = '6Gi'
DBCPU = '4'
DBCapacity = '10Gi'
IsStateful = true
DBArgs = ['shared_buffers=1536MB', 'effective_cache_size=4096MB', 'work_mem=64MB']

[CCIP.Groups]
[CCIP.Groups.load]
KeepEnvAlive = true
NumberOfCommitNodes = 16
MsgType = 'WithoutToken'
PhaseTimeout = '50m'
TestDuration = '1h'
NodeFunding = 1000.0
RequestPerUnitTime = [1]
TimeUnit = '10s'
NoOfRoutersPerPair = 2
NoOfNetworks = 10


[Database]
MaxIdleConns = 10
MaxOpenConns = 20
MigrateOnStartup = true