ChainID = '81'
# FinalityTag will be enabled once the custom tag is implemented
# FinalityTagEnabled = true
FinalityDepth = 100
LogPollInterval = '6s'

[GasEstimator]
EIP1559DynamicFees = false
PriceMax = '100000 gwei'
LimitDefault = 8000000