ChainID = '80084'
# finality_depth: instant
FinalityDepth = 10 
# block_time: 5s, adding 1 second buffer 
LogPollInterval = '6s' 

# finality_depth * block_time / 60 secs = ~0.8  min (finality time)
NoNewFinalizedHeadsThreshold = '5m'

[GasEstimator]
EIP1559DynamicFees = true
Mode = 'FeeHistory'

[GasEstimator.FeeHistory]
# block_time was: 5s, per recommendation skip 1-2 blocks
CacheTimeout = '10s'

[GasEstimator.BlockHistory]
BlockHistorySize = 100

[HeadTracker]
# FinalityDepth < 1k => FinalityTagBypass = false
# https://chainlink-core.slack.com/archives/C07RA1B58CC/p1730983397689179?thread_ts=1730908333.814809&cid=C07RA1B58CC
FinalityTagBypass = false
