ChainID = '808813'
# OP stack https://docs.gobob.xyz/learn/introduction/stack-overview#rollup-layer
ChainType = 'optimismBedrock'
# finality_depth was: ~850
FinalityDepth = 900
# block_time was:  2s
LogPollInterval = '5s'

# finality_depth * block_time / 60 secs = ~30  min (finality time)
NoNewFinalizedHeadsThreshold = '35m'

FinalityTagEnabled = true

[GasEstimator]
EIP1559DynamicFees = true
Mode = 'FeeHistory'

[GasEstimator.FeeHistory]
# block_time was: 2s
CacheTimeout = '2s'

[GasEstimator.BlockHistory]
BlockHistorySize = 100

[HeadTracker]
# FinalityDepth < 1k => FinalityTagBypass = false
# https://chainlink-core.slack.com/archives/C07RA1B58CC/p1730983397689179?thread_ts=1730908333.814809&cid=C07RA1B58CC
FinalityTagBypass = false
