ChainID = '808813'
# OP stack https://docs.gobob.xyz/learn/introduction/stack-overview#rollup-layer
ChainType = 'optimismBedrock'
# FinalityDepth in mainnet showed more than 3k
FinalityDepth = 3150
# block_time was:  2s, adding 1 second buffer
LogPollInterval = '3s'

# finality_depth * block_time / 60 secs = ~105  min (finality time)
NoNewFinalizedHeadsThreshold = '110m'

FinalityTagEnabled = true

[GasEstimator]
EIP1559DynamicFees = true
Mode = 'FeeHistory'

[GasEstimator.FeeHistory]
# block_time was: 2s, per recommendation skip 1-2 blocks
CacheTimeout = '4s'

[GasEstimator.BlockHistory]
BlockHistorySize = 100

[HeadTracker]
# FinalityDepth < 1k => FinalityTagBypass = false
# https://chainlink-core.slack.com/archives/C07RA1B58CC/p1730983397689179?thread_ts=1730908333.814809&cid=C07RA1B58CC
FinalityTagBypass = false
