ChainID = '1123'
FinalityDepth = 2000 # compat test finality_depth: ~1900
LogPollInterval = '5s' # compat test block_time:  ~2s 

NoNewFinalizedHeadsThreshold = '10m' # with 10m threw PLENTY of [RPC's finalized state is out of sync; no new finalized heads received for 10m0s (last finalized head received was 3100170)]

FinalityTagEnabled = true #compat test get_logs>supports_finalized_tag: returned true

[GasEstimator]
EIP1559DynamicFees = true
Mode = 'FeeHistory'

