[[EVM]]
ChainID = "44787"
ChainType = "celo"
FinalityTagEnabled = true
FinalityDepth = 2750
LogPollInterval = "1s"
NoNewHeadsThreshold = "1m"
MinIncomingConfirmations = 1
NoNewFinalizedHeadsThreshold = "45m"

[EVM.GasEstimator]
EIP1559DynamicFees = true
PriceMin = "5 gwei"
PriceMax = "1000 gwei"
BumpMin = "2 gwei"

[EVM.GasEstimator.BlockHistory]
BlockHistorySize = 60

[EVM.Transactions]
ResendAfterThreshold = "30s"

[EVM.HeadTracker]
HistoryDepth = 2750

[EVM.NodePool]
SyncThreshold = 10

[EVM.OCR]
ContractConfirmations = 1