ChainID = '44787'
ChainType = 'celo'
FinalityTagEnabled = true
LogPollInterval = '5s'
MinIncomingConfirmations = 1
NoNewHeadsThreshold = '1m'
OCR.ContractConfirmations = 1

[GasEstimator]
EIP1559DynamicFees = true
PriceDefault = '5 gwei'
PriceMax = '1000 gwei'
PriceMin = '5 gwei'
BumpMin = '2 gwei'
LimitDefault = 8000000

[GasEstimator.BlockHistory]
BlockHistorySize = 24