ChainID = '21000001'
ChainType = 'arbitrum'
FinalityTagEnabled = true
LinkContractAddress = '0x996EfAb6011896Be832969D91E9bc1b3983cfdA1'
NoNewHeadsThreshold = '0'
OCR.ContractConfirmations = 1
LogPollInterval = '1s'

[GasEstimator]
Mode = 'Arbitrum'
LimitMax = 1_000_000_000
# Arbitrum uses the suggested gas price, so we don't want to place any limits on the minimum
PriceMin = '0'
PriceDefault = '0.1 gwei'
PriceMax = '1000 gwei'

[GasEstimator.BlockHistory]
# Force an error if someone set GAS_UPDATER_ENABLED=true by accident; we never want to run the block history estimator on arbitrum
BlockHistorySize = 0