ChainID = '1666700000'
LinkContractAddress = '0x8b12Ac23BFe11cAb03a634C1F117D64a7f2cFD3e'
LogPollInterval = '2s'
MinIncomingConfirmations = 1
NoNewHeadsThreshold = '30s'

[GasEstimator]
PriceDefault = '5 gwei'

[HeadTracker]
# FinalityDepth < 1k => FinalityTagBypass = false
# https://chainlink-core.slack.com/archives/C07RA1B58CC/p1730983397689179?thread_ts=1730908333.814809&cid=C07RA1B58CC
FinalityTagBypass = false
