ChainID = '59144'
FinalityTagEnabled = false
FinalityDepth = 600 #3s block time ~ 20m finality based on committee decision
NoNewHeadsThreshold = '0' #No empty blocks

[HeadTracker]
HistoryDepth = 1000

[Transactions]
ResendAfterThreshold = '30s'

[GasEstimator]
BumpPercent = 10
BumpThreshold = 10
EIP1559DynamicFees = true
FeeCapDefault = '2500 gwei'
TipCapDefault = '5 gwei'
TipCapMin = '1 gwei'
LimitDefault = 8000000

[GasEstimator.BlockHistory]
BlockHistorySize = 200
CheckInclusionBlocks = 0 #required for AutoPurge zkoverflow replacement

[Transactions.AutoPurge]
Enabled = true
Threshold = 50 # 50 blocks at 3s block time ~2.5 minutes
MinAttempts = 3