ChainID = '1088'
ChainType = 'metis'
FinalityDepth = 1
MinIncomingConfirmations = 1
NoNewHeadsThreshold = '0'

[GasEstimator]
Mode = 'SuggestedPrice'
# Metis uses the SuggestedPrice estimator
PriceMin = '0'
LimitDefault = 8000000

[GasEstimator.BlockHistory]
# Force an error if someone enables the estimator by accident; we never want to run the block history estimator on metisaa
BlockHistorySize = 0

[NodePool]
SyncThreshold = 10

[OCR]
ContractConfirmations = 1