ChainID = '1101'
ChainType = 'zkevm'
FinalityTagEnabled = true
FinalityDepth = 1000
# checks how long to wait before after receiving "NoHeads" & marking RPC out of sync.
# This chain in the past have had inconsistent block rate
# average block rate of zkEVM based on past data
LogPollInterval = '30s'
# some concerns that subscription gave Heads much earlier than the RPC polling so
# setting this to 15
RPCBlockQueryDelay = 15
# node configured default batch size.
# ref: https://github.com/smartcontractkit/chainlink/pull/11962
RPCDefaultBatchSize = 100

[OCR]
ContractConfirmations = 1

[Transactions]
# chain in the past have had inconsistent block rate
ResendAfterThreshold = '3m'

[Transactions.AutoPurge]
Enabled = true
MinAttempts = 3

[GasEstimator]
Mode = 'FeeHistory'
# The FeeHistory estimator does not enforce PriceMin, setting it to 0 to not place any limits on the price
PriceMin = '0'
BumpPercent = 40

[GasEstimator.FeeHistory]
# Refresh the suggested price every 4 seconds, to stay slightly below their polling rate of 5s
CacheTimeout = '4s'

[HeadTracker]
HistoryDepth = 2000