ChainID = '1101'
FinalityTagEnabled = true
NoNewHeadsThreshold = '6m'
MinIncomingConfirmations = 1
LogPollInterval = '30s'
RPCBlockQueryDelay = 15
RPCDefaultBatchSize = 100

[Transactions]
ResendAfterThreshold = '3m'

[GasEstimator]
PriceMax = '1000 gwei'
PriceMin = '100 mwei'
FeeCapDefault = '1000 gwei'
BumpPercent = 40
BumpMin = '100 mwei'
LimitDefault = 8000000

[GasEstimator.BlockHistory]
BlockHistorySize = 12