ChainID = "2020"
FinalityTagEnabled = true
LinkContractAddress = "0x3902228D6A3d2Dc44731fD9d45FeE6a61c722D0b"
LogPollInterval = "6s"
NoNewHeadsThreshold = "10m"

[GasEstimator]
PriceMax = "100000 gwei"
PriceDefault = "21 gwei"
PriceMin = "20 gwei"
