ChainID = "2020"
FinalityTagEnabled = true
LinkContractAddress = "0x3902228D6A3d2Dc44731fD9d45FeE6a61c722D0b"
LogPollInterval = "6s"
NoNewHeadsThreshold = "10m"

[GasEstimator]
Mode = 'FeeHistory'
PriceMax = "1000 gwei"
# Ronin gas price is 20gwei by default but setting to 21gwei due to some issues faced during local testing https://docs.skymavis.com/mavis/mpc/guides/estimate-gas#overview.
PriceDefault = "21 gwei"
PriceMin = "20 gwei"
