ChainID = '534352'
FinalityDepth = 10
FinalityTagEnabled = true
ChainType = 'scroll'
LogPollInterval = '5s'
MinIncomingConfirmations = 1
# Scroll only emits blocks when a new tx is received, so this method of liveness detection is not useful
NoNewHeadsThreshold = '0'

[GasEstimator]
# BumpThreshold can be removed from here when core enables bumping for Scroll.
BumpThreshold = 3
LimitDefault = 8000000
EIP1559DynamicFees = true
FeeCapDefault = '1000 gwei'
TipCapDefault = '5 gwei'
TipCapMin = '1 gwei'

[GasEstimator.BlockHistory]
# Default is 8, which leads to bumpy gas prices. In CCIP we want to smooth out
# the gas prices, so we increase the sample size.`
BlockHistorySize = 200

# Scroll has avg finality time of 1 hour and 3 sec/block block rate.
[HeadTracker]
HistoryDepth = 1200

[Transactions.AutoPurge]
Enabled = true
DetectionApiUrl = 'https://venus.scroll.io'

[OCR]
ContractConfirmations = 1