[CCIP]
[CCIP.Env]
Mockserver = 'http://127.1.27.12:1080'

[CCIP.Env.Network]
selected_networks = ['geth_1337', 'geth_2337']

[CCIP.Env.Network.EVMNetworks.geth_1337]
evm_name = 'geth_1337'
evm_chain_id = 1337
evm_urls = ['ws://127.1.27.15:8546']
evm_http_urls = ['http://127.1.27.15:8544']
evm_keys = ['ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80']
evm_simulated = true
client_implementation = 'Ethereum'
evm_chainlink_transaction_limit = 500000
evm_transaction_timeout = '2m'
evm_minimum_confirmations = 1
evm_gas_estimation_buffer = 10000
evm_supports_eip1559 = true
evm_default_gas_limit = 6000000

[CCIP.Env.Network.EVMNetworks.geth_2337]
evm_name = 'geth_2337'
evm_chain_id = 2337
evm_urls = ['ws://127.1.27.6:8546']
evm_http_urls = ['http://127.1.27.6:8544']
evm_keys = ['59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d']
evm_simulated = true
client_implementation = 'Ethereum'
evm_chainlink_transaction_limit = 500000
evm_transaction_timeout = '2m'
evm_minimum_confirmations = 1
evm_gas_estimation_buffer = 10000
evm_supports_eip1559 = true
evm_default_gas_limit = 6000000


[CCIP.Env.ExistingCLCluster]
Name = 'crib-ani'
NoOfNodes = 6

[[CCIP.Env.ExistingCLCluster.NodeConfigs]]
URL = 'https://crib-ani-node1.main.stage.cldev.sh/'
Email = 'notreal@fakeemail.ch'
Password = 'fj293fbBnlQ!f9vNs'
InternalIP = 'app-node-1'


[[CCIP.Env.ExistingCLCluster.NodeConfigs]]
URL = 'https://crib-ani-node2.main.stage.cldev.sh/'
Email = 'notreal@fakeemail.ch'
Password = 'fj293fbBnlQ!f9vNs'
InternalIP = 'app-node-2'

[[CCIP.Env.ExistingCLCluster.NodeConfigs]]
URL = 'https://crib-ani-node3.main.stage.cldev.sh/'
Email = 'notreal@fakeemail.ch'
Password = 'fj293fbBnlQ!f9vNs'
InternalIP = 'app-node-3'

[[CCIP.Env.ExistingCLCluster.NodeConfigs]]
URL = 'https://crib-ani-node4.main.stage.cldev.sh/'
Email = 'notreal@fakeemail.ch'
Password = 'fj293fbBnlQ!f9vNs'
InternalIP = 'app-node-4'

[[CCIP.Env.ExistingCLCluster.NodeConfigs]]
URL = 'https://crib-ani-node5.main.stage.cldev.sh/'
Email = 'notreal@fakeemail.ch'
Password = 'fj293fbBnlQ!f9vNs'
InternalIP = 'app-node-5'

[[CCIP.Env.ExistingCLCluster.NodeConfigs]]
URL = 'https://crib-ani-node6.main.stage.cldev.sh/'
Email = 'notreal@fakeemail.ch'
Password = 'fj293fbBnlQ!f9vNs'
InternalIP = 'app-node-6'

[CCIP.Groups]
[CCIP.Groups.smoke]
LocalCluster = false
TestRunName = 'crib-ani-smoke'

[CCIP.Groups.load]
LocalCluster = false
TestRunName = 'crib-ani-load'
TimeUnit = '1s'
TestDuration = '20m'
RequestPerUnitTime = [1]
NodeFunding = 100.0
