ccipScriptsDeployment:
  enabled: false
  image: ccip-scripts-image:image-tag
  # oidc role name required to upload job output to S3
  oidcRoleARN: arn:aws:iam::123456789012:role/example
  outputBucketName: example
chains:
  - NetworkId: 1337
    ChainId: geth_1337
    WalletKey: "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
    DeployLink: true
    DeployWETH: true
    ChainConfig:
      EvmChainId: 1337
      GasSettings:
        EIP1559: true
        GasTipCap: 1000000000
      FeeTokens:
        - "ChainLink Token"
        - "WETH"
      WrappedNative: "WETH"
      Router: "0x0000000000000000000000000000000000000000"
      ARM: "0x0000000000000000000000000000000000000000"
      ARMProxy: "0x0000000000000000000000000000000000000000"
      PriceRegistry: "0x0000000000000000000000000000000000000000"
      DeploySettings:
        DeployARM: true
        DeployTokenPools: true
        DeployRouter: true
        DeployPriceRegistry: true
      TunableChainValues:
        FinalityDepth: 1
        OptimisticConfirmations: 1
        MaxGasPrice: 200000000000
  - NetworkId: 2337
    ChainId: geth_2337
    WalletKey: "59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"
    DeployLink: true
    DeployWETH: true
    ChainConfig:
      EvmChainId: 2337
      GasSettings:
        EIP1559: true
        GasTipCap: 1000000000
      FeeTokens:
        - "ChainLink Token"
        - "WETH"
      WrappedNative: "WETH"
      Router: "0x0000000000000000000000000000000000000000"
      ARM: "0x0000000000000000000000000000000000000000"
      ARMProxy: "0x0000000000000000000000000000000000000000"
      PriceRegistry: "0x0000000000000000000000000000000000000000"
      DeploySettings:
        DeployARM: true
        DeployTokenPools: true
        DeployRouter: true
        DeployPriceRegistry: true
      TunableChainValues:
        FinalityDepth: 1
        OptimisticConfirmations: 1
        MaxGasPrice: 200000000000
LaneDeploySettings:
  geth_1337,geth_2337:
    DeployLane: true
    DeployPingPongDapp: true
CCIPLaneConfigs:
  geth_1337:
  geth_2337:
chainlink:
  web_port: 6688
  nodes:
    - name: node-1
    - name: node-2
    - name: node-3
    - name: node-4
    - name: node-5
    - name: node-6
geth:
  wsRpcPort: 8546
networkPolicies:
  enabled: true