// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	common "github.com/ethereum/go-ethereum/common"
	ccipdata "github.com/smartcontractkit/chainlink/v2/core/services/ocr2/plugins/ccip/internal/ccipdata"

	context "context"

	mock "github.com/stretchr/testify/mock"

	rpclib "github.com/smartcontractkit/chainlink/v2/core/services/ocr2/plugins/ccip/internal/rpclib"
)

// TokenPoolReader is an autogenerated mock type for the TokenPoolReader type
type TokenPoolReader struct {
	mock.Mock
}

// Address provides a mock function with given fields:
func (_m *TokenPoolReader) Address() common.Address {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 common.Address
	if rf, ok := ret.Get(0).(func() common.Address); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Address)
		}
	}

	return r0
}

// GetInboundTokenPoolRateLimitCall provides a mock function with given fields:
func (_m *TokenPoolReader) GetInboundTokenPoolRateLimitCall() (rpclib.EvmCall, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInboundTokenPoolRateLimitCall")
	}

	var r0 rpclib.EvmCall
	var r1 error
	if rf, ok := ret.Get(0).(func() (rpclib.EvmCall, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() rpclib.EvmCall); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(rpclib.EvmCall)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInboundTokenPoolRateLimits provides a mock function with given fields: ctx, pools
func (_m *TokenPoolReader) GetInboundTokenPoolRateLimits(ctx context.Context, pools []ccipdata.TokenPoolReader) ([]ccipdata.TokenBucketRateLimit, error) {
	ret := _m.Called(ctx, pools)

	if len(ret) == 0 {
		panic("no return value specified for GetInboundTokenPoolRateLimits")
	}

	var r0 []ccipdata.TokenBucketRateLimit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []ccipdata.TokenPoolReader) ([]ccipdata.TokenBucketRateLimit, error)); ok {
		return rf(ctx, pools)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []ccipdata.TokenPoolReader) []ccipdata.TokenBucketRateLimit); ok {
		r0 = rf(ctx, pools)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ccipdata.TokenBucketRateLimit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []ccipdata.TokenPoolReader) error); ok {
		r1 = rf(ctx, pools)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTokenPoolReader creates a new instance of TokenPoolReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenPoolReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenPoolReader {
	mock := &TokenPoolReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
