// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ArmChainState is an autogenerated mock type for the ArmChainState type
type ArmChainState struct {
	mock.Mock
}

// ForceValidateNotCursed provides a mock function with given fields: ctx
func (_m *ArmChainState) ForceValidateNotCursed(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ForceValidateNotCursed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateNotCursed provides a mock function with given fields: ctx
func (_m *ArmChainState) ValidateNotCursed(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ValidateNotCursed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewArmChainState creates a new instance of ArmChainState. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArmChainState(t interface {
	mock.TestingT
	Cleanup(func())
}) *ArmChainState {
	mock := &ArmChainState{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
