// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ReportVerifier is an autogenerated mock type for the ReportVerifier type
type ReportVerifier struct {
	mock.Mock
}

// VerifyReports provides a mock function with given fields: ctx, signedReports
func (_m *ReportVerifier) VerifyReports(ctx context.Context, signedReports [][]byte) error {
	ret := _m.Called(ctx, signedReports)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, [][]byte) error); ok {
		r0 = rf(ctx, signedReports)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewReportVerifier creates a new instance of ReportVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportVerifier {
	mock := &ReportVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
