#!/usr/bin/env bash

set -e

# src/v0.8/ccip/models/Internal.sol
# src/v0.8/ccip/models/RateLimiter.sol
# src/v0.8/ccip/MerkleMultiProof.sol
# excluded because Foundry doesn't support coverage on library files


lcov --remove $1 -o $2 \
  '*/ccip/test/*' \
  '*/vendor/*' \
  'src/v0.8/ccip/ocr/OCR2Abstract.sol' \
  'src/v0.8/ccip/models/Internal.sol' \
  'src/v0.8/ccip/models/RateLimiter.sol' \
  'src/v0.8/ccip/MerkleMultiProof.sol' \
  'src/v0.8/ConfirmedOwnerWithProposal.sol' \
  'src/v0.8/tests/MockV3Aggregator.sol' \
  'src/v0.8/ccip/applications/ImmutableExample.sol' \
  'src/v0.8/ccip/applications/ImmutableExample.sol' \
  'src/v0.8/ccip/pools/tokens/*' \
  --rc lcov_branch_coverage=1
