#!/usr/bin/env bash

set -euo pipefail
VERSION=v1.13.7
SHASUM=26d44b460db497b3a5b75d5c7ad47b87e6bd398bb3821c321e36e71de3104893

echo "Installing solana@${VERSION}"
curl -sSfL https://release.solana.com/$VERSION/install --output install_solana.sh \
    && echo "Checking shasum of Solana install script." \
    && echo "${SHASUM} install_solana.sh" | sha256sum --check
chmod +x install_solana.sh
sh -c ./install_solana.sh
