// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: core/services/synchronization/telem/telem_ccip.proto

package telem

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CCIPExecutionReportSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LenMessages          uint32 `protobuf:"varint,1,opt,name=len_messages,json=lenMessages,proto3" json:"len_messages,omitempty"`
	LenOffchainTokenData uint32 `protobuf:"varint,2,opt,name=len_offchain_token_data,json=lenOffchainTokenData,proto3" json:"len_offchain_token_data,omitempty"`
}

func (x *CCIPExecutionReportSummary) Reset() {
	*x = CCIPExecutionReportSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_services_synchronization_telem_telem_ccip_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CCIPExecutionReportSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCIPExecutionReportSummary) ProtoMessage() {}

func (x *CCIPExecutionReportSummary) ProtoReflect() protoreflect.Message {
	mi := &file_core_services_synchronization_telem_telem_ccip_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCIPExecutionReportSummary.ProtoReflect.Descriptor instead.
func (*CCIPExecutionReportSummary) Descriptor() ([]byte, []int) {
	return file_core_services_synchronization_telem_telem_ccip_proto_rawDescGZIP(), []int{0}
}

func (x *CCIPExecutionReportSummary) GetLenMessages() uint32 {
	if x != nil {
		return x.LenMessages
	}
	return 0
}

func (x *CCIPExecutionReportSummary) GetLenOffchainTokenData() uint32 {
	if x != nil {
		return x.LenOffchainTokenData
	}
	return 0
}

// The CCIPCommitReport message is used to report the latest commit
// as it's seend by the node.
type CCIPCommitReportSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LenTokenPriceUpdates          uint32 `protobuf:"varint,1,opt,name=len_token_price_updates,json=lenTokenPriceUpdates,proto3" json:"len_token_price_updates,omitempty"`
	PriceUpdatesDestChainSelector uint64 `protobuf:"varint,2,opt,name=price_updates_dest_chain_selector,json=priceUpdatesDestChainSelector,proto3" json:"price_updates_dest_chain_selector,omitempty"`
	PriceUpdatesUsdPerUnitGas     []byte `protobuf:"bytes,3,opt,name=price_updates_usd_per_unit_gas,json=priceUpdatesUsdPerUnitGas,proto3" json:"price_updates_usd_per_unit_gas,omitempty"` // big.Int
	Epoch                         uint32 `protobuf:"varint,4,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Round                         uint32 `protobuf:"varint,5,opt,name=round,proto3" json:"round,omitempty"`
}

func (x *CCIPCommitReportSummary) Reset() {
	*x = CCIPCommitReportSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_services_synchronization_telem_telem_ccip_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CCIPCommitReportSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCIPCommitReportSummary) ProtoMessage() {}

func (x *CCIPCommitReportSummary) ProtoReflect() protoreflect.Message {
	mi := &file_core_services_synchronization_telem_telem_ccip_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCIPCommitReportSummary.ProtoReflect.Descriptor instead.
func (*CCIPCommitReportSummary) Descriptor() ([]byte, []int) {
	return file_core_services_synchronization_telem_telem_ccip_proto_rawDescGZIP(), []int{1}
}

func (x *CCIPCommitReportSummary) GetLenTokenPriceUpdates() uint32 {
	if x != nil {
		return x.LenTokenPriceUpdates
	}
	return 0
}

func (x *CCIPCommitReportSummary) GetPriceUpdatesDestChainSelector() uint64 {
	if x != nil {
		return x.PriceUpdatesDestChainSelector
	}
	return 0
}

func (x *CCIPCommitReportSummary) GetPriceUpdatesUsdPerUnitGas() []byte {
	if x != nil {
		return x.PriceUpdatesUsdPerUnitGas
	}
	return nil
}

func (x *CCIPCommitReportSummary) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *CCIPCommitReportSummary) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

type CCIPTelemWrapper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//	*CCIPTelemWrapper_CommitReport
	//	*CCIPTelemWrapper_ExecutionReport
	Msg isCCIPTelemWrapper_Msg `protobuf_oneof:"msg"`
}

func (x *CCIPTelemWrapper) Reset() {
	*x = CCIPTelemWrapper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_services_synchronization_telem_telem_ccip_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CCIPTelemWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCIPTelemWrapper) ProtoMessage() {}

func (x *CCIPTelemWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_core_services_synchronization_telem_telem_ccip_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCIPTelemWrapper.ProtoReflect.Descriptor instead.
func (*CCIPTelemWrapper) Descriptor() ([]byte, []int) {
	return file_core_services_synchronization_telem_telem_ccip_proto_rawDescGZIP(), []int{2}
}

func (m *CCIPTelemWrapper) GetMsg() isCCIPTelemWrapper_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *CCIPTelemWrapper) GetCommitReport() *CCIPCommitReportSummary {
	if x, ok := x.GetMsg().(*CCIPTelemWrapper_CommitReport); ok {
		return x.CommitReport
	}
	return nil
}

func (x *CCIPTelemWrapper) GetExecutionReport() *CCIPExecutionReportSummary {
	if x, ok := x.GetMsg().(*CCIPTelemWrapper_ExecutionReport); ok {
		return x.ExecutionReport
	}
	return nil
}

type isCCIPTelemWrapper_Msg interface {
	isCCIPTelemWrapper_Msg()
}

type CCIPTelemWrapper_CommitReport struct {
	CommitReport *CCIPCommitReportSummary `protobuf:"bytes,1,opt,name=commit_report,json=commitReport,proto3,oneof"`
}

type CCIPTelemWrapper_ExecutionReport struct {
	ExecutionReport *CCIPExecutionReportSummary `protobuf:"bytes,2,opt,name=execution_report,json=executionReport,proto3,oneof"`
}

func (*CCIPTelemWrapper_CommitReport) isCCIPTelemWrapper_Msg() {}

func (*CCIPTelemWrapper_ExecutionReport) isCCIPTelemWrapper_Msg() {}

var File_core_services_synchronization_telem_telem_ccip_proto protoreflect.FileDescriptor

var file_core_services_synchronization_telem_telem_ccip_proto_rawDesc = []byte{
	0x0a, 0x34, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f,
	0x73, 0x79, 0x6e, 0x63, 0x68, 0x72, 0x6f, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x74, 0x65, 0x6c, 0x65, 0x6d, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x5f, 0x63, 0x63, 0x69, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x22, 0x76, 0x0a,
	0x1a, 0x43, 0x43, 0x49, 0x50, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x6c,
	0x65, 0x6e, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0b, 0x6c, 0x65, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x35,
	0x0a, 0x17, 0x6c, 0x65, 0x6e, 0x5f, 0x6f, 0x66, 0x66, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x14, 0x6c, 0x65, 0x6e, 0x4f, 0x66, 0x66, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x44, 0x61, 0x74, 0x61, 0x22, 0x89, 0x02, 0x0a, 0x17, 0x43, 0x43, 0x49, 0x50, 0x43, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x79, 0x12, 0x35, 0x0a, 0x17, 0x6c, 0x65, 0x6e, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x14, 0x6c, 0x65, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x48, 0x0a, 0x21, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x5f, 0x64, 0x65, 0x73, 0x74, 0x5f, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x1d, 0x70, 0x72, 0x69, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x73, 0x44, 0x65, 0x73, 0x74, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x12, 0x41, 0x0a, 0x1e, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x73, 0x5f, 0x75, 0x73, 0x64, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x75, 0x6e, 0x69, 0x74,
	0x5f, 0x67, 0x61, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x19, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x55, 0x73, 0x64, 0x50, 0x65, 0x72, 0x55, 0x6e,
	0x69, 0x74, 0x47, 0x61, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e,
	0x64, 0x22, 0xb0, 0x01, 0x0a, 0x10, 0x43, 0x43, 0x49, 0x50, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x57,
	0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x12, 0x45, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x74, 0x65, 0x6c, 0x65, 0x6d, 0x2e, 0x43, 0x43, 0x49, 0x50, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x48, 0x00, 0x52,
	0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x4e, 0x0a,
	0x10, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x2e,
	0x43, 0x43, 0x49, 0x50, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x48, 0x00, 0x52, 0x0f, 0x65, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x42, 0x05, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x42, 0x4e, 0x5a, 0x4c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x6b, 0x69, 0x74, 0x2f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x2f, 0x76, 0x32,
	0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x73,
	0x79, 0x6e, 0x63, 0x68, 0x72, 0x6f, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x74,
	0x65, 0x6c, 0x65, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_services_synchronization_telem_telem_ccip_proto_rawDescOnce sync.Once
	file_core_services_synchronization_telem_telem_ccip_proto_rawDescData = file_core_services_synchronization_telem_telem_ccip_proto_rawDesc
)

func file_core_services_synchronization_telem_telem_ccip_proto_rawDescGZIP() []byte {
	file_core_services_synchronization_telem_telem_ccip_proto_rawDescOnce.Do(func() {
		file_core_services_synchronization_telem_telem_ccip_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_services_synchronization_telem_telem_ccip_proto_rawDescData)
	})
	return file_core_services_synchronization_telem_telem_ccip_proto_rawDescData
}

var file_core_services_synchronization_telem_telem_ccip_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_core_services_synchronization_telem_telem_ccip_proto_goTypes = []interface{}{
	(*CCIPExecutionReportSummary)(nil), // 0: telem.CCIPExecutionReportSummary
	(*CCIPCommitReportSummary)(nil),    // 1: telem.CCIPCommitReportSummary
	(*CCIPTelemWrapper)(nil),           // 2: telem.CCIPTelemWrapper
}
var file_core_services_synchronization_telem_telem_ccip_proto_depIdxs = []int32{
	1, // 0: telem.CCIPTelemWrapper.commit_report:type_name -> telem.CCIPCommitReportSummary
	0, // 1: telem.CCIPTelemWrapper.execution_report:type_name -> telem.CCIPExecutionReportSummary
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_core_services_synchronization_telem_telem_ccip_proto_init() }
func file_core_services_synchronization_telem_telem_ccip_proto_init() {
	if File_core_services_synchronization_telem_telem_ccip_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_services_synchronization_telem_telem_ccip_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CCIPExecutionReportSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_services_synchronization_telem_telem_ccip_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CCIPCommitReportSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_services_synchronization_telem_telem_ccip_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CCIPTelemWrapper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_core_services_synchronization_telem_telem_ccip_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*CCIPTelemWrapper_CommitReport)(nil),
		(*CCIPTelemWrapper_ExecutionReport)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_services_synchronization_telem_telem_ccip_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_services_synchronization_telem_telem_ccip_proto_goTypes,
		DependencyIndexes: file_core_services_synchronization_telem_telem_ccip_proto_depIdxs,
		MessageInfos:      file_core_services_synchronization_telem_telem_ccip_proto_msgTypes,
	}.Build()
	File_core_services_synchronization_telem_telem_ccip_proto = out.File
	file_core_services_synchronization_telem_telem_ccip_proto_rawDesc = nil
	file_core_services_synchronization_telem_telem_ccip_proto_goTypes = nil
	file_core_services_synchronization_telem_telem_ccip_proto_depIdxs = nil
}
