// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: core/services/synchronization/telem/telem_ccip.proto

package telem

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CCIPBlockNumber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp    uint64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	BlockNumber  uint64 `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	BlockHash    string `protobuf:"bytes,3,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	ConfigDigest []byte `protobuf:"bytes,4,opt,name=config_digest,json=configDigest,proto3" json:"config_digest,omitempty"`
}

func (x *CCIPBlockNumber) Reset() {
	*x = CCIPBlockNumber{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_services_synchronization_telem_telem_ccip_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CCIPBlockNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCIPBlockNumber) ProtoMessage() {}

func (x *CCIPBlockNumber) ProtoReflect() protoreflect.Message {
	mi := &file_core_services_synchronization_telem_telem_ccip_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCIPBlockNumber.ProtoReflect.Descriptor instead.
func (*CCIPBlockNumber) Descriptor() ([]byte, []int) {
	return file_core_services_synchronization_telem_telem_ccip_proto_rawDescGZIP(), []int{0}
}

func (x *CCIPBlockNumber) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CCIPBlockNumber) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *CCIPBlockNumber) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *CCIPBlockNumber) GetConfigDigest() []byte {
	if x != nil {
		return x.ConfigDigest
	}
	return nil
}

type CCIPNodeVersion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp    uint64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	NodeVersion  string `protobuf:"bytes,2,opt,name=node_version,json=nodeVersion,proto3" json:"node_version,omitempty"`
	ConfigDigest []byte `protobuf:"bytes,3,opt,name=config_digest,json=configDigest,proto3" json:"config_digest,omitempty"`
}

func (x *CCIPNodeVersion) Reset() {
	*x = CCIPNodeVersion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_services_synchronization_telem_telem_ccip_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CCIPNodeVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCIPNodeVersion) ProtoMessage() {}

func (x *CCIPNodeVersion) ProtoReflect() protoreflect.Message {
	mi := &file_core_services_synchronization_telem_telem_ccip_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCIPNodeVersion.ProtoReflect.Descriptor instead.
func (*CCIPNodeVersion) Descriptor() ([]byte, []int) {
	return file_core_services_synchronization_telem_telem_ccip_proto_rawDescGZIP(), []int{1}
}

func (x *CCIPNodeVersion) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CCIPNodeVersion) GetNodeVersion() string {
	if x != nil {
		return x.NodeVersion
	}
	return ""
}

func (x *CCIPNodeVersion) GetConfigDigest() []byte {
	if x != nil {
		return x.ConfigDigest
	}
	return nil
}

type CCIPTelemWrapper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//	*CCIPTelemWrapper_BlockNumber
	//	*CCIPTelemWrapper_NodeVersion
	Msg isCCIPTelemWrapper_Msg `protobuf_oneof:"msg"`
}

func (x *CCIPTelemWrapper) Reset() {
	*x = CCIPTelemWrapper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_services_synchronization_telem_telem_ccip_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CCIPTelemWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCIPTelemWrapper) ProtoMessage() {}

func (x *CCIPTelemWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_core_services_synchronization_telem_telem_ccip_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCIPTelemWrapper.ProtoReflect.Descriptor instead.
func (*CCIPTelemWrapper) Descriptor() ([]byte, []int) {
	return file_core_services_synchronization_telem_telem_ccip_proto_rawDescGZIP(), []int{2}
}

func (m *CCIPTelemWrapper) GetMsg() isCCIPTelemWrapper_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *CCIPTelemWrapper) GetBlockNumber() *CCIPBlockNumber {
	if x, ok := x.GetMsg().(*CCIPTelemWrapper_BlockNumber); ok {
		return x.BlockNumber
	}
	return nil
}

func (x *CCIPTelemWrapper) GetNodeVersion() *CCIPNodeVersion {
	if x, ok := x.GetMsg().(*CCIPTelemWrapper_NodeVersion); ok {
		return x.NodeVersion
	}
	return nil
}

type isCCIPTelemWrapper_Msg interface {
	isCCIPTelemWrapper_Msg()
}

type CCIPTelemWrapper_BlockNumber struct {
	BlockNumber *CCIPBlockNumber `protobuf:"bytes,1,opt,name=block_number,json=blockNumber,proto3,oneof"`
}

type CCIPTelemWrapper_NodeVersion struct {
	NodeVersion *CCIPNodeVersion `protobuf:"bytes,2,opt,name=node_version,json=nodeVersion,proto3,oneof"`
}

func (*CCIPTelemWrapper_BlockNumber) isCCIPTelemWrapper_Msg() {}

func (*CCIPTelemWrapper_NodeVersion) isCCIPTelemWrapper_Msg() {}

var File_core_services_synchronization_telem_telem_ccip_proto protoreflect.FileDescriptor

var file_core_services_synchronization_telem_telem_ccip_proto_rawDesc = []byte{
	0x0a, 0x34, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f,
	0x73, 0x79, 0x6e, 0x63, 0x68, 0x72, 0x6f, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x74, 0x65, 0x6c, 0x65, 0x6d, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x5f, 0x63, 0x63, 0x69, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x22, 0x96, 0x01,
	0x0a, 0x0f, 0x43, 0x43, 0x49, 0x50, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12,
	0x21, 0x0a, 0x0c, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x68, 0x61, 0x73, 0x68,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73,
	0x68, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x64, 0x69, 0x67, 0x65,
	0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x22, 0x77, 0x0a, 0x0f, 0x43, 0x43, 0x49, 0x50, 0x4e, 0x6f,
	0x64, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e,
	0x6f, 0x64, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x5f, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x22,
	0x93, 0x01, 0x0a, 0x10, 0x43, 0x43, 0x49, 0x50, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x57, 0x72, 0x61,
	0x70, 0x70, 0x65, 0x72, 0x12, 0x3b, 0x0a, 0x0c, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x65, 0x6c,
	0x65, 0x6d, 0x2e, 0x43, 0x43, 0x49, 0x50, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x48, 0x00, 0x52, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x3b, 0x0a, 0x0c, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x2e,
	0x43, 0x43, 0x49, 0x50, 0x4e, 0x6f, 0x64, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x48,
	0x00, 0x52, 0x0b, 0x6e, 0x6f, 0x64, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x05,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x42, 0x4e, 0x5a, 0x4c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x6b, 0x69, 0x74, 0x2f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x2f, 0x76,
	0x32, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f,
	0x73, 0x79, 0x6e, 0x63, 0x68, 0x72, 0x6f, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x74, 0x65, 0x6c, 0x65, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_services_synchronization_telem_telem_ccip_proto_rawDescOnce sync.Once
	file_core_services_synchronization_telem_telem_ccip_proto_rawDescData = file_core_services_synchronization_telem_telem_ccip_proto_rawDesc
)

func file_core_services_synchronization_telem_telem_ccip_proto_rawDescGZIP() []byte {
	file_core_services_synchronization_telem_telem_ccip_proto_rawDescOnce.Do(func() {
		file_core_services_synchronization_telem_telem_ccip_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_services_synchronization_telem_telem_ccip_proto_rawDescData)
	})
	return file_core_services_synchronization_telem_telem_ccip_proto_rawDescData
}

var file_core_services_synchronization_telem_telem_ccip_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_core_services_synchronization_telem_telem_ccip_proto_goTypes = []interface{}{
	(*CCIPBlockNumber)(nil),  // 0: telem.CCIPBlockNumber
	(*CCIPNodeVersion)(nil),  // 1: telem.CCIPNodeVersion
	(*CCIPTelemWrapper)(nil), // 2: telem.CCIPTelemWrapper
}
var file_core_services_synchronization_telem_telem_ccip_proto_depIdxs = []int32{
	0, // 0: telem.CCIPTelemWrapper.block_number:type_name -> telem.CCIPBlockNumber
	1, // 1: telem.CCIPTelemWrapper.node_version:type_name -> telem.CCIPNodeVersion
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_core_services_synchronization_telem_telem_ccip_proto_init() }
func file_core_services_synchronization_telem_telem_ccip_proto_init() {
	if File_core_services_synchronization_telem_telem_ccip_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_services_synchronization_telem_telem_ccip_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CCIPBlockNumber); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_services_synchronization_telem_telem_ccip_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CCIPNodeVersion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_services_synchronization_telem_telem_ccip_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CCIPTelemWrapper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_core_services_synchronization_telem_telem_ccip_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*CCIPTelemWrapper_BlockNumber)(nil),
		(*CCIPTelemWrapper_NodeVersion)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_services_synchronization_telem_telem_ccip_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_services_synchronization_telem_telem_ccip_proto_goTypes,
		DependencyIndexes: file_core_services_synchronization_telem_telem_ccip_proto_depIdxs,
		MessageInfos:      file_core_services_synchronization_telem_telem_ccip_proto_msgTypes,
	}.Build()
	File_core_services_synchronization_telem_telem_ccip_proto = out.File
	file_core_services_synchronization_telem_telem_ccip_proto_rawDesc = nil
	file_core_services_synchronization_telem_telem_ccip_proto_goTypes = nil
	file_core_services_synchronization_telem_telem_ccip_proto_depIdxs = nil
}
