ChainID = '59902'
ChainType = 'optimismBedrock'
FinalityDepth = 10
FinalityTagEnabled = true
MinIncomingConfirmations = 1
NoNewHeadsThreshold = '0'
OCR.ContractConfirmations = 1

[GasEstimator]
Mode = 'SuggestedPrice'
PriceMin = '0'

[GasEstimator.BlockHistory]
BlockHistorySize = 0

[NodePool]
SyncThreshold = 10

[HeadTracker]
# FinalityDepth < 1k => FinalityTagBypass = false
# https://chainlink-core.slack.com/archives/C07RA1B58CC/p1730983397689179?thread_ts=1730908333.814809&cid=C07RA1B58CC
FinalityTagBypass = false