ChainID = "2021"
FinalityTagEnabled = true
LinkContractAddress = "0x5bB50A6888ee6a67E22afFDFD9513be7740F1c15"
LogPollInterval = "6s"
NoNewHeadsThreshold = "10m"

[GasEstimator]
PriceDefault = "21 gwei"
PriceMin = "20 gwei"
