{{- if and .Values.networkPolicies.enabled .Values.ccipScriptsDeployment.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ccip-scripts-network-policy
spec:
  podSelector:
    matchLabels:
      app: ccip-scripts-deployer
  policyTypes:
    - Egress
  egress:
    - ports:
        - protocol: TCP
          port: 443
{{- end }}