{{- if $.Values.ccipScriptsDeployment.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ccip-scripts-deployer
  annotations:
    "eks.amazonaws.com/role-arn": {{$.Values.ccipScriptsDeployment.oidcRoleARN}}

{{- end }}