{{- if $.Values.deployContractsAndJobs }}
apiVersion: batch/v1
kind: Job
metadata:
  name: ccip-scripts-deployer
  labels:
    app: ccip-scripts-deployer
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    prometheus.io/scrape: 'true'
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        app: ccip-scripts-deployer
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      initContainers:
        - name: wait-for-nodes
          image: {{.Values.ccipScriptsImage}}
          volumeMounts:
            - name: scripts-volume
              mountPath: /scripts
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsUser: 999
            runAsGroup: 999
            runAsNonRoot: true
          command:
            - bash
            - /scripts/wait_for_endpoint.sh
            {{- with (index $.Values.chainlink.nodes 0) }}
            - "http://{{$.Release.Name}}-{{.name}}.{{$.Release.Namespace}}.svc.cluster.local:{{$.Values.chainlink.web_port}}"
            {{- end }}
      containers:
        - name: ccip-scripts
          image: {{.Values.ccipScriptsImage}}
          env:
            - name: CONFIG_JSON_PATH
              value: /data/config.json
          command: [ "pilot.test", "-test.v" ]
          volumeMounts:
            - name: config-volume
              mountPath: /data
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsUser: 999
            runAsGroup: 999
            runAsNonRoot: true
      restartPolicy: Never
      volumes:
        - name: config-volume
          configMap:
            name: ccip-scripts-config
        - name: scripts-volume
          configMap:
            defaultMode: 0755
            name: ccip-scripts-scripts
  backoffLimit: 0
{{- end}}