name: Automation Load Test
on:
  workflow_dispatch:
    inputs:
      base64Config:
        description: base64-ed config
        required: true
        type: string      
      slackMemberID:
        description: Notifies test results (Not your @)
        required: true
        default: U02Q14G80TY
        type: string

jobs:
  automation_load:
    environment: integration
    permissions:
      checks: write
      pull-requests: write
      id-token: write
      contents: read
      actions: read
    name: Automation Load Test
    runs-on: ubuntu22.04-16cores-64GB
    env:
      SLACK_API_KEY: ${{ secrets.QA_SLACK_API_KEY }}
      SLACK_CHANNEL: C03KJ5S7KEK
      CHAINLINK_ENV_USER: ${{ github.actor }}
      REF_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
    - name: Setup GAP Staging env
      uses: smartcontractkit/.github/actions/setup-gap@1bc7ce34fa81fffcb4a6eb0e4e12e59d94d0fc8f # setup-gap@0.2.0
      with:
        aws-role-arn: ${{ secrets.AWS_OIDC_IAM_ROLE_INTEGRATION_TESTING_STAGE_ARN }}
        api-gateway-host: ${{ secrets.AWS_API_GW_HOST_K8S_STAGE }}
        aws-region: ${{ secrets.AWS_REGION }}
        ecr-private-registry: ${{ secrets.AWS_ACCOUNT_ID_PROD }}
        k8s-cluster-name: ${{ secrets.AWS_K8S_CLUSTER_NAME_STAGE }}
        use-private-ecr-registry: true
        use-k8s: true
        metrics-job-name: "e2e-load-test"
        gc-host: ${{ secrets.GRAFANA_INTERNAL_HOST }}
        gc-basic-auth: ${{ secrets.GRAFANA_INTERNAL_BASIC_AUTH }}
    - name: Test kubectl
      shell: bash
      run: |
        # test create
        timestamp="$(date +%s)"
        kubectl -n wasp create cm "test-create-ccip-$timestamp"
        
        # this should fail, we shouldn't be able to access resources in other ns
        kubectl -n mercury get pods