name: "Build lint and test CCIP-OCR3"

on:
  pull_request:
    paths:
      - core/services/ocr3/plugins/ccip/**

jobs:
  build-lint-test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version: ['1.21']
    defaults:
      run:
        working-directory: ./core/services/ocr3/plugins/ccip
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version
      - name: Build
        run: go build -v ./...
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.59.0
      - name: Run golangci-lint
        run: golangci-lint run
      - name: Test with the Go CLI
        run: go test -v ./...