name: Chain Selectors Version Check

on:
  push:
    branches:
      - ccip-develop
      - release/*
    tags:
      - v*
  pull_request:
    branches:
      - release/*


jobs:
  verify-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Setup Go
        uses: ./.github/actions/setup-go
        with:
          only-modules: true
          go-version-file: "go.mod"

      - name: Get chain-selectors version
        id: get-chain-selectors-version
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          version_mismatch=false
          latest_chain_selector_version=$(gh release view -R smartcontractkit/chain-selectors --json tagName --jq '.tagName')

          echo "Latest chain-selectors version: $latest_chain_selector_version"

          directories=$(find . -name 'go.mod' -exec dirname {} \;)

          set +e
          for directory in $directories; do
            echo "Checking $directory"

            pushd "$directory" > /dev/null || return
            chain_selector_version=$(go list -m -f '{{.Version}}' github.com/smartcontractkit/chain-selectors)
            popd > /dev/null || return

            echo "$directory - current version: $chain_selector_version"

            if [[ -z "$chain_selector_version" ]]; then
              continue
            fi

            if [[ "$chain_selector_version" != "$latest_chain_selector_version" ]]; then
              echo "::error::Version mismatch for $directory - current version: $chain_selector_version, latest version on Github: $latest_chain_selector_version"
              version_mismatch=true
            fi
          done
          set -e

          if [[ "$version_mismatch" = true ]]; then
            exit 1
          else
            echo "All chain-selectors versions are up to date"
            exit 0
          fi
